# This is a basic workflow to help you get started with Actions

name: Redeploy on GCloudVM

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Check out repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            # Runs a single command using the runners shell

            - name: Create SSH key
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
                  sudo chmod 600 ~/.ssh/private.key
                  ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
              shell: bash
              env:
                  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
                  SSH_HOST: ${{secrets.SSH_HOST}}

            - name: Redeploy using SSH
              run: |
                  ssh -i ~/.ssh/private.key -tt $SSH_USERNAME@$SSH_HOST << EOF
                    cd $BOT_PATH
                    git pull
                    npm run production
                    exit
                  EOF
              env:
                  SSH_USERNAME: ${{secrets.SSH_USERNAME}}
                  SSH_HOST: ${{secrets.SSH_HOST}}
                  BOT_PATH: ${{secrets.BOT_PATH}}

            - name: Clears the ssh key
              run: rm ~/.ssh/private.key

            - name: Clears known_hosts file
              run: rm ~/.ssh/known_hosts

            - name: Clears the bash history
              run: history -c
